cc_binary(
    name = "state_machine",
    srcs = [
        "selectable.h",
        "state_machine_node.cc",
    ],
    deps = [
        "//third_party/roscpp:libros",
        "//third_party/std_msgs:Bool",
        "//third_party/std_srvs:SetBool",
    ],
)
